### ISSUE TITLE
A problem in the paper Probabilistic 3D Multi-Object Tracking for Autonomous Driving 

### ISSUE THREAD

**Issue by Kins1ley** [eddyhkchiu/mahalanobis_3d_multi_object_tracking#12]
Hi, when I read your paper "Probabilistic 3D Multi-Object Tracking for Autonomous Driving ", I noticed that when you calculate the distance between observation state and predicted state, it seems that you just treat the observation state as random variable. 
![image](https://user-images.githubusercontent.com/26199647/83229923-70b3a880-a1bb-11ea-829f-7e943f6e5359.png)
And the _matrix S_ is the covariance matrix of random variable, observation state. But actually the observation state and predicted state are both random variable and the _noise matrix R_ should belong to observation state according to the kalman filter algorithm.
![image](https://user-images.githubusercontent.com/26199647/83230038-a8baeb80-a1bb-11ea-8df9-00774cb56505.png)

**Comment by Kins1ley** [comment]
According to the definition of Mahalanobis Distance, 
![image](https://user-images.githubusercontent.com/26199647/83318262-94332d80-a265-11ea-9d5a-c9dad3494445.png)
x and y should obey the same distribution, but according to the Kalman Filter, they actually obey different distributions ,right? It seems that there exists conflict.

**Comment by eddyhkchiu** [comment]
Hi, we measure the distance between one observation and one prediction using the Mahalanobis distance. The observation in our paper is just the 3D object detection result from the MEGVII detector. For the prediction, we treat it as random variables, having mean /miu and covariance /Sigma values. The observation model noise covariance matrix R was used to generate the Kalman gain and the above mean /miu and covariance /Sigma, also the innovation covariance S of the prediction based on the Kalman Filter Algorithm.
