### ISSUE TITLE
some doubt about ablation experiment?

### ISSUE THREAD

**Issue by AndyYuan96** [eddyhkchiu/mahalanobis_3d_multi_object_tracking#14]
Hi, thank you for opensource the project, I have some question about paper ablation experiment result, I just wonder whether the result : "AB3DMOT [8] * 50.9 21.8 74.3 69.4 39.0 58.7 35.3 58.1" use your data-driven covariance matrix estimation? As I see the data-driven covariance matrix estimation give the most improvement compared to others like greedy algorithm.

**Comment by eddyhkchiu** [comment]
Hi, Thanks! The experiment "AB3DMOT[8] *" is our implementation of [8], which still uses [8]'s original non-data-driven covariance matrix from their github code. As described in README, in our repo, you can run the script 
"python main.py val 0 iou 0.1 h false nuscenes results/000001;
python evaluate_nuscenes.py --output_dir results/000001 results/000001/val/results_val_probabilistic_tracking.json > results/000001/output.txt" 
to reproduce this "AB3DMOT[8] *" result.

**Comment by AndyYuan96** [comment]
> Hi, Thanks! The experiment "AB3DMOT[8] *" is our implementation of [8], which still uses [8]'s original non-data-driven covariance matrix from their github code. As described in README, in our repo, you can run the script
> "python main.py val 0 iou 0.1 h false nuscenes results/000001;
> python evaluate_nuscenes.py --output_dir results/000001 results/000001/val/results_val_probabilistic_tracking.json > results/000001/output.txt"
> to reproduce this "AB3DMOT[8] *" result.

Did you try to use the data-driven covariance matrix estimation in AB3DMOT,  as the data-driven covariance matrix give too much improvement, maybe after using data-driven covariance matrix , AB3DMOT' result is higher than your method?

**Comment by eddyhkchiu** [comment]
We did not include that experiment in the paper, but that can be done by using the following script:
"python main.py val 2 iou 0.1 h false nuscenes results/000009;
python evaluate_nuscenes.py --output_dir results/000009 results/000009/val/results_val_probabilistic_tracking.json > results/000009/output.txt"

And here are the results:
Overall: 49.0
bicycle: 22.3
bus: 73.9
car: 68.1
motorcycle: 39.0
pedestrian: 47.3
trailer: 34.8
truck: 57.8

This overall AMOTA (49.0) is still worse than our proposed method (56.1). The main reason is that AB3DMOT uses 3D-IOU as the distance measurement, and our method uses Mahalanobis distance.  Our other ablation experiments in Table 1 also show that using Mahalanobis distance is better than using 3D-IOU.

**Comment by deepmeng** [comment]
> We did not include that experiment in the paper, but that can be done by using the following script:
> "python main.py val 2 iou 0.1 h false nuscenes results/000009;
> python evaluate_nuscenes.py --output_dir results/000009 results/000009/val/results_val_probabilistic_tracking.json > results/000009/output.txt"
> 
> And here are the results:
> Overall: 49.0
> bicycle: 22.3
> bus: 73.9
> car: 68.1
> motorcycle: 39.0
> pedestrian: 47.3
> trailer: 34.8
> truck: 57.8
> 
> This overall AMOTA (49.0) is still worse than our proposed method (56.1). The main reason is that AB3DMOT uses 3D-IOU as the distance measurement, and our method uses Mahalanobis distance. Our other ablation experiments in Table 1 also show that using Mahalanobis distance is better than using 3D-IOU.

In your provided script 'python main.py val 2 iou 0.1 h false nuscenes results/000009', there is a big problem. You set the 'covariance_id=2'. However, the covariance was calculated from Nuscenes dataset. I am worried that this covariance cannot be applied directly to AB3DMOT and KITTI.
