### ISSUE TITLE
some interesting result about how much improvement mahalanbis_distance and data-driven covariance given? 

### ISSUE THREAD

**Issue by AndyYuan96** [eddyhkchiu/mahalanobis_3d_multi_object_tracking#15]
Hi, I jus think that mahalanobis distance and data-driven give too much improvment, so I do an experiment, I change the mahalanbis_distance distance to l2 norm of x and y when matching tracker and detections, and use the default covariance of AB3DMOT. And the result is very close to your paper result?
Aggregated results:
AMOTA	0.555
AMOTP	0.831
RECALL	0.605
MOTAR	0.787
GT	14556
MOTA	0.478
MOTP	0.405
MT	3374
ML	1819
FAF	42.6
TP	72344
FP	12453
FN	28724
IDS	829
FRAG	765
TID	1.14
LGD	1.55
Eval time: 3078.3s

Your paper did have improvement, but not too much.

**Comment by eddyhkchiu** [comment]
Thanks for sharing the experiment and the result.
