### ISSUE TITLE
What is the execution time for tracking of 3D objects per frame basuis on an average?

### ISSUE THREAD

**Issue by chowkamlee81** [eddyhkchiu/mahalanobis_3d_multi_object_tracking#4]
What is the execution time for tracking of 3D objects per frame? Kindly help

**Comment by eddyhkchiu** [comment]
Hi, 
The tracking speed is roughly 10 frames per second. My tracking code will print out the execution time after finishing the tracking.

**Comment by sergiev** [comment]
@eddyhkchiu could you give us your hardware specs, please?

**Comment by eddyhkchiu** [comment]
Hi,
The CPU is Intel Xeon Gold 5118 CPU @ 2.30GHz.
