### ISSUE TITLE
How to get matrix values of P,Q,R in covariance.py?

### ISSUE THREAD

**Issue by chowkamlee81** [eddyhkchiu/mahalanobis_3d_multi_object_tracking#6]
How to get matrix values of P,Q,R in covariance.py?

Kindly help

**Comment by eddyhkchiu** [comment]
The values come from the result of executing "python get_nuscenes_stats.py". We estimate the P, Q, and R based on the statistics of the training set data. And the detailed algorithm can be seen in section 3.6 of our paper https://arxiv.org/pdf/2001.05673.pdf.
